tinyMCE.addI18n('pl.advimage_dlg',{
tab_general:"Podstawowe",
tab_appearance:"Wygląd",
tab_advanced:"Rozszerzone",
general:"Podstawowe",
title:"Tytuł",
preview:"Podgląd",
constrain_proportions:"Proporcjonalnie",
langdir:"Kierunek tekstu",
langcode:"Kod języka",
long_desc:"Poszerzony opis odnośnika",
style:"Styl CSS",
classes:"Klasa CSS",
ltr:"Od lewej do prawej",
rtl:"Od prawej do lewej",
id:"ID",
map:"Mapa obrazu",
swap_image:"Podmiana obrazu",
alt_image:"Tekst alternatywny",
mouseover:"Wskaźnik myszki nad",
mouseout:"Wskaźnik myszki poza",
misc:"Różne",
example_img:"Przykładowe grafiki",
missing_alt:"Czy na pewno chcesz kontynuować bez dodania alternatywnego opisu obrazka? Bez tego opisu materiał nie będzie w pełni zrozumiały dla osób niepełnosprawnych oraz gdy użytkownik korzysta z przeglądarki nie wyświetlającej obrazków bądź wyłączył ich wyświetlanie.",
dialog_title:"Wstaw modyfikuj obraz",
src:"Adres obrazka",
alt:"Opis obrazka",
list:"Lista obrazków",
border:"Obramowanie",
dimensions:"Rozmiary",
vspace:"Odstępy obok",
hspace:"Odstępy nad i pod",
align:"Wyrównanie",
align_baseline:"Linia bazowa",
align_top:"Góra",
align_middle:"Środek",
align_bottom:"Dół",
align_texttop:"Góra tekstu",
align_textbottom:"Dół tekstu",
align_left:"Po lewej",
align_right:"Po prawej",
image_list:"Lista obrazków"
});