tinyMCE.addI18n('pl.advlink_dlg',{
title:"Wstaw/Zodyfikuj odnośnik",
url:"Adres łącza",
target:"Cel",
titlefield:"Tytuł",
is_email:"Podane łącze wydaje się być adresem pocztowym - czy dodać protokół: mailto:?",
is_external:"Podane łącze wydaje się być zewnętrznym adresem internetowym - czy dodać protokół http://?",
list:"Lista odnośników",
general_tab:"Podstawowe",
popup_tab:"Okno dodatkowe",
events_tab:"Zdarzenia",
advanced_tab:"Rozszerzone",
general_props:"Podstawowe właściwości",
popup_props:"Właściwości okna dodatkowego",
event_props:"Zdarzenia",
advanced_props:"Rozszerzone właściwości",
popup_opts:"Opcje",
anchor_names:"Zakładka (kotwica)",
target_same:"Otwórz w tym oknie/ramce",
target_parent:"Otwórz w oknie/ramce rodzica",
target_top:"Otwórz w głównym oknie (zastąpi wszystkie ramki)",
target_blank:"Otwórz w nowym oknie",
popup:"Okno JavaScript",
popup_url:"Adres okna",
popup_name:"Nazwa okna",
popup_return:"Wstaw instrukcję 'return false'",
popup_scrollbars:"Pokaż pasek przewijania",
popup_statusbar:"Pokaż pasek stanu",
popup_toolbar:"Pokaż pasek narzędzi",
popup_menubar:"Show menu bar",
popup_location:"Pokaż pasek adresu",
popup_resizable:"Utwórz okno skalowalne",
popup_dependent:"Zależne (tylko Mozilla/Firefox)",
popup_size:"Rozmiar",
popup_position:"Pozycja (X/Y)",
id:"ID",
style:"Style",
classes:"Klasy",
target_name:"Okno docelowe",
langdir:"Kierunek pisma",
target_langcode:"Docelowy kod języka",
langcode:"Kod języka",
encoding:"Kodowanie znaków",
mime:"Typ Mime",
rel:"Relacja strony do celu (rel)",
rev:"Relacja celu do strony (rev)",
tabindex:"Indeks tabulatora",
accesskey:"Klawisz dostępu",
ltr:"Od lewej do prawej",
rtl:"Od prawej do lewej",
link_list:"Lista odnośników"
});