tinyMCE.addI18n('pl.fullpage_dlg',{
title:"Właściwości dokumentu",
meta_tab:"Podstawowe",
appearance_tab:"Wygląd",
advanced_tab:"Rozszerzone",
meta_props:"Meta information",
langprops:"Język i kodowanie",
meta_title:"Tytuł",
meta_keywords:"Słowa kluczowe",
meta_description:"Opis",
meta_robots:"Roboty",
doctypes:"Doctype",
langcode:"Kod języka",
langdir:"Kierunek pisma",
ltr:"Od lewej do prawej",
rtl:"Od prawej do lewej",
xml_pi:"Deklaracja XML",
encoding:"Kodowanie znaków",
appearance_bgprops:"Właściwości tła",
appearance_marginprops:"Marginesy elementu body",
appearance_linkprops:"Kolor odnośników",
appearance_textprops:"Własności tekstu",
bgcolor:"Kolor tła",
bgimage:"Obrazek tła",
left_margin:"Lewy margines",
right_margin:"Prawy margines",
top_margin:"Górny margines",
bottom_margin:"Dolny margines",
text_color:"Kolor tekstu",
font_size:"Rozmiar czcionki",
font_face:"Krój czcionki",
link_color:"Odnośnik nieodwiedzony",
hover_color:"Odnośnik wskazywany",
visited_color:"Odnośnik odwiedzony",
active_color:"Odnośnik aktywny",
textcolor:"Kolor tekstu",
fontsize:"Rozmiar czcionki",
fontface:"Krój czcionki",
meta_index_follow:"Indeksuj stronę i strony wskazywane przez odnośniki",
meta_index_nofollow:"Indeksuj stronę, ale nie indeksuj wskazywanych przez odnośniki",
meta_noindex_follow:"Nie indeksuj strony, indeksuj strony wskazywane przez odnośniki",
meta_noindex_nofollow:"Nie indeksuj i nie podążaj za odnośnikami",
appearance_style:"Arkusze i właściwości stylów",
stylesheet:"Arkusz stylów",
style:"Styl",
author:"Autor",
copyright:"Prawa własności",
add:"Dodaj nowy element",
remove:"Usuń zaznaczony element",
moveup:"Przenieś zaznaczony element w górę",
movedown:"Przenieś zaznaczony element w dół",
head_elements:"Elementy: head",
info:"Informacje",
add_title:"Element: title",
add_meta:"Element: meta",
add_script:"Element: script",
add_style:"Element: style",
add_link:"Element: link",
add_base:"Element: base",
add_comment:"Atrybut: comment",
title_element:"Element: title",
script_element:"Element: script",
style_element:"Element: style",
base_element:"Element: base",
link_element:"Element: link",
meta_element:"Element: meta",
comment_element:"Atrybut: comment",
src:"Ścieżka",
language:"Język",
href:"Odnośnik",
target:"Cel",
type:"Type",
charset:"Kodowanie",
defer:"Odroczenie",
media:"Media",
properties:"Właściwości",
name:"Nazwa",
value:"Wartość",
content:"Treść",
rel:"Rel",
rev:"Rev",
hreflang:"Język odnośnika",
general_props:"Podstawowe",
advanced_props:"Rozszerzone"
});