tinyMCE.addI18n('pl.xhtmlxtras_dlg',{
attribute_label_title:"Tytuł",
attribute_label_id:"ID",
attribute_label_class:"Klasa",
attribute_label_style:"Styl",
attribute_label_cite:"Cytat",
attribute_label_datetime:"Data/Czas",
attribute_label_langdir:"Kierunek tekstu",
attribute_option_ltr:"Od lewej do prawej",
attribute_option_rtl:"Od prawej do lewej",
attribute_label_langcode:"Język",
attribute_label_tabindex:"Indeks tabulatora",
attribute_label_accesskey:"Klawisz dostępu",
attribute_events_tab:"Zdarzenia",
attribute_attrib_tab:"Atrybuty",
general_tab:"Podstawowe",
attrib_tab:"Atrybuty",
events_tab:"Zdarzenia",
fieldset_general_tab:"Ustawienia podstawowe",
fieldset_attrib_tab:"Atrybuty elementu",
fieldset_events_tab:"Zdarzenia elementu",
title_ins_element:"Element Wstawione",
title_del_element:"Element Usunięte",
title_acronym_element:"Element Akronim",
title_abbr_element:"Element Skrót",
title_cite_element:"Element Cytat",
remove:"Usunięcie",
insert_date:"Wstaw aktualną datę/czas",
option_ltr:"Od lewej do prawej",
option_rtl:"Od prawej do lewej",
attribs_title:"Wstaw/zmień atrybuty"

});