tinyMCE.addI18n('pl.dlg',{
// JCE specific
modified: 'Zmieniony',
file: 'Plik',
folder: 'Katalog',
files: 'pliki',
folders: 'katalogi',
comments: 'Komentarz',
size: 'Rozmiar',
preview: 'Podgląd',
duration: 'Czas trwania',
dimensions: 'Wymiary',
contents: 'Zawartość',
unwritable: 'Niezapisywalny',
bad_name: 'Niepoprawna nazwa pliku lub katalogu',
message_tree: 'Generowanie drzewa...',
message_load: 'Wczytywanie...',
message_properties: 'Pobieranie właściwości...',
current_dir: 'Aktualny katalog to: ',
help: 'Pomoc',
name: 'Nazwa',
uploading: 'Wczytywanie...',
upload: 'Wczytaj',
queue: 'Kolejka',
upload_exits: 'Czynność, gdy plik istnieje: ',
overwrite: 'Nadpisz plik',
unique: 'Utwórz nową nazwę',
cancel: 'Anuluj',
ok: 'OK',
browse: 'Przeglądaj',
'options': 'Opcje',
'confirm': 'Potwierdź',
yes: 'Tak',
no: 'Nie',
'alert': 'Uwaga',
new_folder: 'Nowy katalog',
rename: 'Zmień nazwę',
'delete': 'Usuń',
delete_folder_alert: 'Usunąć katalog?',
delete_file_alert: 'Usunąć plik/pliki?',
rename_folder: 'Zmień nazwę katalogu',
rename_file: 'Zmień nazwę pliku',
rename_alert: 'Zmiana nazwy pliku/katalogu spowoduje zerwanie połączeń w istniejących odnośnikach. Kontynuować?',
file_select: 'Kliknij nazwę pliku, aby go wstawić. Zobacz szczegóły pliku po prawej stronie. Aby zaznaczyć kilka, przytrzymaj klawisz CTRL.',
notwritable: 'Niezapisywalny',
notwritable_desc: 'Niezapisywalny: Plik lub katalog jest niezapisywalny i nie może być usunięty, zmieniony ani przeniesiony.',
bad_name: 'Niepoprawna nazwa pliku lub katalogu',
bad_name_desc: 'Niepoprawna nazwa pliku lub katalogu: Nazwa może zawierać tylko znaki a-z0-9_-.',
select_value: 'Dodaj wartość'
});