tinyMCE.addI18n('pl.media_dlg',{
title:"Wstaw/Modyfikuj plik multimedialny",
general:"Podstawowe",
advanced:"Rozszerzone",
file:"Plik/Adres",
list:"Lista",
size:"Wymiary",
preview:"Podgląd",
constrain_proportions:"Zachowaj proporcje",
type:"Typ",
id:"ID",
name:"Nazwa",
class_name:"Klasa",
vspace:"Odstępy obok",
hspace:"Odstępy nad i pod",
play:"Odtwórz",
loop:"Powtarzaj",
menu:"Pokaż menu",
quality:"Jakość",
scale:"Skala",
align:"Wyrównanie",
salign:"Dopasowanie",
wmode:"Tryb okna",
bgcolor:"Kolor tła",
base:"Adres bazowy",
flashvars:"Zmienne Flash",
liveconnect:"SWLiveConnect",
autohref:"AutoHREF",
cache:"Pamięć podręczna",
hidden:"Ukrycie",
controller:"Kontroler dźwięku",
kioskmode:"Tryb kiosku",
playeveryframe:"Odtwarzaj każdą klatkę",
targetcache:"Target cache",
correction:"Bez korekcji",
enablejavascript:"Włącz JavaScript",
starttime:"Czas rozpoczęcia",
endtime:"Czas zakończenia",
href:"Href",
qtsrcchokespeed:"Zmniejsz tempo",
target:"Cel",
volume:"Głośność",
autostart:"Auto start",
enabled:"Włączony",
fullscreen:"Pełny ekran",
invokeurls:"Zdalny URL",
mute:"Wycisz",
stretchtofit:"Dostosuj do",
windowlessvideo:"Windowless video",
balance:"Balans",
baseurl:"URL bazowy",
captioningid:"Id podpisu",
currentmarker:"Oznacz aktualne",
currentposition:"Aktualna pozycja",
defaultframe:"Domyślna ramka",
playcount:"Ilość powtórzeń",
rate:"Tempo",
uimode:"UI Mode",
flash_options:"Opcje Flasha",
qt_options:"Opcje Quicktime",
wmp_options:"Opcje Windows media player",
rmp_options:"Opcje Real media player",
shockwave_options:"Opcje Shockwave",
autogotourl:"Idź automatycznie do URL",
center:"Środek",
imagestatus:"Stan grafiki",
maintainaspect:"Maintain aspect",
nojava:"Bez Java",
prefetch:"Wybierz z wyprzedzeniem",
shuffle:"Mieszaj",
console:"Konsola",
numloop:"Ilość powtórzeń",
controls:"Kontrola",
scriptcallbacks:"Skrypt odpowiedzi",
swstretchstyle:"Styl rozciągnięcia",
swstretchhalign:"Rozciągnięcie w poziomie",
swstretchvalign:"Rozciągnięcie w pionie",
sound:"Melodia",
progress:"Progresja",
qtsrc:"QT Src",
qt_stream_warn:"Źródła mediów strumieniowych rtsp mogą być dodane do pola QT na karcie opcji rozszerzonych.\nW polu SRC możesz również dodać niestrumieniowe wersję medium.",
align_top:"Góra",
align_right:"Prawa",
align_bottom:"Dół",
align_left:"Lewa",
align_center:"Środek",
align_top_left:"Góra lewa",
align_top_right:"Góra prawa",
align_bottom_left:"Dół lewa",
align_bottom_right:"Dół prawa",
flv_options:"Opcje filmików Flasha",
flv_scalemode:"Scale mode",
flv_buffer:"Buffer",
flv_startimage:"Start image",
flv_starttime:"Czas rozpoczęcia",
flv_defaultvolume:"Domyślna głośność",
flv_hiddengui:"Ukryte GUI",
flv_autostart:"Auto start",
flv_loop:"Powtarzaj",
flv_showscalemodes:"Show scale modes",
flv_smoothvideo:"Smooth video",
flv_jscallback:"JS Callback"
});