// PL lang variables utf-8
// ***********************************************************************
// ** Title.........:    TinyMCE polish lang. Plugins: table
// ** Version.......:    1.0
// ** Author........:    Stefan Wajda <zwiastun@zwiastun.net>,
// ** Filename......:    pl.js (polish language file)
// ** Last changed..:    13/06/2006
// ***********************************************************************/

tinyMCE.addToLang('table',{
general_tab : 'Ogólne',
advanced_tab : 'Rozszerzone',
general_props : 'Podstawowe właściwości',
advanced_props : 'Rozszerzone właściwości',
desc : 'Wstaw nową tabelę',
row_before_desc : 'Wstaw wiersz przed',
row_after_desc : 'Wstaw wiersz po',
delete_row_desc : 'Usuń wiersz',
col_before_desc : 'Wstaw kolumnę przed',
col_after_desc : 'Wstaw kolumnę po',
delete_col_desc : 'Usuń kolumnę',
rowtype : 'Wiersz w części tabeli',
title : 'Wstaw/Modyfikuj tabelę',
width : 'Szerokość',
height : 'Wysokość',
cols : 'Kolumny',
rows : 'Wiersze',
cellspacing : 'Odstęp&nbsp;między komórkami',
cellpadding : 'Odstęp&nbsp;wewnątrz komórek',
border : 'Obramowanie',
align : 'Wyrównanie.',
align_default : 'Domyślnie',
align_left : 'Do lewej',
align_right : 'Do prawej',
align_middle : 'Wyśrodkuj',
row_title : 'Właściwości wiersza',
cell_title : 'Właściwości komórki',
cell_type : 'Typ komórki',
row_desc : 'Właściwości wiersza',
cell_desc : 'Właściwości komórki',
valign : 'Wyrównanie pionowe',
align_top : 'do góry',
align_bottom : 'do dołu',
props_desc : 'Właściwości tabeli',
bordercolor : 'Kolor obramowania',
bgcolor : 'Kolor tła',
merge_cells_title : 'Scal komórki',
split_cells_desc : 'Podziel komórkę',
merge_cells_desc : 'Scal komórki',
cut_row_desc : 'Wytnij wiersz',
copy_row_desc : 'Kopiuj wiersz',
paste_row_before_desc : 'Wklej wiersz przed',
paste_row_after_desc : 'Wklej wiersz poniżej',
id : 'ID',
style: 'Styl CSS',
langdir : 'Kierunek tekstu',
langcode : 'Kod języka',
mime : 'Typ MIME',
ltr : 'Od lewej do prawej',
rtl : 'Od prawej do lewej',
bgimage : 'Obrazek tła',
summary : 'Streszczenie',
td : "Dane",
th : "Nagłówek",
cell_cell : 'Zmodyfikuj aktualną komórkę',
cell_row : 'Zmodyfikuj wszystkie komórki w rzędzie',
cell_all : 'Zmodyfikuj wszystkie komórki w tabeli',
row_row : 'Zmodyfikuj aktualny wiersz',
row_odd : 'Zmodyfikuj nieparzyste wiersze',
row_even : 'Zmodyfikuj parzyste wiersze',
row_all : 'Zmodyfikuj wszystkie wiersze',
thead : 'Nagłówek tabeli',
tbody : 'Środek tabeli',
tfoot : 'Stopka tabeli',
del : 'Usuń tabelę',
scope : 'Zakres',
row : 'Wiersz',
col : 'Kolumna',
rowgroup : 'Grupuj wiersze',
colgroup : 'Grupuj kolumny',
col_limit : 'Osiągnięto maksymalną ilość kolumn {$cols}.',
row_limit : 'Osiągnięto maksymalną ilość wierszy {$rows}.',
cell_limit : 'Osiągnięto maksymalną ilość komórek {$cells}.',
missing_scope: 'Czy na pewno chcesz kontynuować bez określenia zakreu komórek obejmowanych nagłówkiem. Bez podania tej informacji zrozumienie zawartości tabeli może być trudne np. dla osób niewidzących, korzystających ze specjalistycznego oprogramowania odczytującego treść tabeli.',
caption : 'Podpis tabeli'
});
