tinyMCE.addI18n('pl.table_dlg',{
general_tab:"Ogólne",
advanced_tab:"Rozszerzone",
general_props:"Podstawowe właściwości",
advanced_props:"Rozszerzone właściwości",
rowtype:"Wiersz w części tabeli",
title:"Wstaw/Modyfikuj tabelę",
width:"Szerokość",
height:"Wysokość",
cols:"Kolumny",
rows:"Wiersze",
cellspacing:"Odstęp&nbsp;między komórkami",
cellpadding:"Odstęp&nbsp;wewnątrz komórek",
border:"Obramowanie",
align:"Wyrównanie",
align_default:"Domyślnie",
align_left:"Do lewej",
align_right:"Do prawej",
align_middle:"Wyśrodkuj",
row_title:"Właściwości wiersza",
cell_title:"Właściwości komórki",
cell_type:"Typ komórki",
valign:"Wyrównanie pionowe",
align_top:"do góry",
align_bottom:"do dołu",
bordercolor:"Kolor obramowania",
bgcolor:"Kolor tła",
merge_cells_title:"Scal komórki",
id:"ID",
style:"Styl CSS",
langdir:"Kierunek tekstu",
langcode:"Kod języka",
mime:"Typ MIME",
ltr:"Od lewej do prawej",
rtl:"Od prawej do lewej",
bgimage:"Obrazek tła",
summary:"Streszczenie",
td:"Dane",
th:"Nagłówek",
cell_cell:"Zmodyfikuj aktualną komórkę",
cell_row:"Zmodyfikuj wszystkie komórki w rzędzie",
cell_all:"Zmodyfikuj wszystkie komórki w tabeli",
row_row:"Zmodyfikuj aktualny wiersz",
row_odd:"Zmodyfikuj nieparzyste wiersze",
row_even:"Zmodyfikuj parzyste wiersze",
row_all:"Zmodyfikuj wszystkie wiersze",
thead:"Nagłówek tabeli",
tbody:"Środek tabeli",
tfoot:"Stopka tabeli",
scope:"Zakres",
rowgroup:"Grupuj wiersze",
colgroup:"Grupuj kolumny",
col_limit:"Osiągnięto maksymalną ilość kolumn {$cols}.",
row_limit:"Osiągnięto maksymalną ilość wierszy {$rows}.",
cell_limit:"Osiągnięto maksymalną ilość komórek {$cells}.",
missing_scope:"Czy na pewno chcesz kontynuować bez określenia zakresu komórek obejmowanych nagłówkiem. Bez podania tej informacji zrozumienie zawartości tabeli może być trudne np. dla osób niewidzących, korzystających ze specjalistycznego oprogramowania odczytującego treść tabeli.",
caption:"Podpis tabeli",
frame:"Obramowanie",
frame_none:"brak",
frame_groups:"pomiędzy grupami",
frame_rows:"pomiędzy wierszami",
frame_cols:"pomiędzy kolumnami",
frame_all:"wszystkie",
rules:"Linie wewnętrzne",
rules_void:"bez linii",
rules_above:"górny brzeg",
rules_below:"dolny brzeg",
rules_hsides:"górny i dolny brzeg",
rules_lhs:"lewy brzeg",
rules_rhs:"prawy brzeg",
rules_vsides:"lewy i prawy brzeg",
rules_box:"wszystkie brzegi",
rules_border:"otoczka"
});