tinyMCE.addI18n('pl.style_dlg',{
title:"Edytor stylów CSS",
apply:"Zastosuj",
text_tab:"Tekst",
background_tab:"Tło",
block_tab:"Blok",
box_tab:"Otoczka",
border_tab:"Obwódka",
list_tab:"Lista",
positioning_tab:"Pozycjonowanie",
text_props:"Tekst",
text_font:"Czcionka",
text_size:"Rozmiar",
text_weight:"Grubość",
text_style:"Styl",
text_variant:"Wariant",
text_lineheight:"Grubość linii",
text_case:"Wielkość znaków",
text_color:"Kolor tekstu",
text_decoration:"Ozdobniki",
text_overline:"Nadkreślenie",
text_underline:"Podkreślenie",
text_striketrough:"Przekreślenie",
text_blink:"Migotanie",
text_none:"Brak",
background_color:"Kolor tła",
background_image:"Obrazek tła",
background_repeat:"Powtarzanie",
background_attachment:"Załącznik",
background_hpos:"Pozycja w poziomie",
background_vpos:"Pozycja w pionie",
block_wordspacing:"Odstęp między słowami",
block_letterspacing:"Odstęp między literami",
block_vertical_alignment:"Wyrównanie w pionie",
block_text_align:"Wyrównanie tekstu",
block_text_indent:"Wcięcie tekstu",
block_whitespace:"Białe znaki",
block_display:"Tryb wyświetlania",
box_width:"Szerokość",
box_height:"Wysokość",
box_float:"Opływanie",
box_clear:"Tamowanie",
padding:"Odstęp",
same:"Tak samo",
top:"Góra",
right:"Prawo",
bottom:"Dół",
left:"Lewo",
margin:"Margines",
style:"Styl",
width:"Szerokość",
height:"Wysokość",
color:"Kolor",
list_type:"Typ listy",
bullet_image:"Obrazek punktora",
position:"Pozycja",
positioning_type:"Pozycjonowanie",
visibility:"Widoczność",
zindex:"Stos",
overflow:"Wypływanie",
placement:"Rozmieszcznie",
clip:"Przycięcie"
});