tinyMCE.addI18n('pl.imgmanager_ext_dlg',{
missing_alt: "Brak opisu obrazka. Bez tego opisu materiał nie będzie w pełni zrozumiały dla niektórych osób niepełnosprawnych oraz dla osób używających przeglądarek tekstowych lub tych, które mają wyłączone wyświetlanie obrazków w przeglądarce.",
delta_width: 0,
delta_height: 0,
'-90': '90&deg; CW',
'90': '90&deg; CCW',
'180': '180&deg;',
'vertical': 'Odbij pionowo',
'horizontal': 'Odbij poziomo',
'view_images': 'Widok miniatur',
'view_list': 'Widok listy',
'use_thumbnail': 'Użyć dołączonej miniatury?',
'resize': 'Zmień rozmiar',
'rotate': 'Obróć',
'proportional': 'Proporcjonalnie',
'cropped': 'Przytnij',
'mode': 'Tryb',
'quality': 'Jakość',
'size': 'Rozmiar',
'thumbnail': 'Miniatura',
'transform': 'Przekształć',
'width': 'Szerokość',
'height': 'Wysokość',
'create_thumbnail': 'Utworzyć miniaturę?',
'delete_thumbnail': 'Usunąć miniaturę?',
'required_jceutilities': 'Wymaga dodatku JCE Utilities',
'required_script': 'Wymaga dodatkowego skryptu',
'required_window': 'Wymaga komponentu JCE Administration',
'message_images': 'Kliknij obrazek, aby zobaczyć szczegóły, kliknij dwa razy, aby wstawić. Przytrzymaj CTRL, aby zaznaczyć kilka obrazków.',
'message_list': 'Kliknij nazwę pliku, aby go wstawić. Kliknięcie wywołuje po prawej stronie jego podgląd i dane. Aby zaznaczyć kilka, przytrzymaj klawisz CTRL.',
no_src: 'Wymagany jest adres. Wskaż obrazek lub wpisz lokalizację.'
});