tinyMCE.addI18n('pl.emotions_dlg',{
title:"Wstaw buźkę",
desc:"Buźki",
cool:"Spoko",
cry:"Płacz",
embarassed:"Wstyd",
foot_in_mouth:"Tajemnica",
frown:"Dezaprobata",
innocent:"Niewinny",
kiss:"Całus",
laughing:"Śmiech",
money_mouth:"Złotousty",
sealed:"Milczenie",
smile:"Uśmiech",
surprised:"Zdziwienie",
tongue_out:"Pokazuję język",
undecided:"Niezdecydowanie",
wink:"Puszcza oczko",
yell:"Krzyk"
});