tinyMCE.addI18n('pl.advanced',{
style_select:"Style",
font_size:"Wielkość czcionki",
fontdefault:"Rodzina czcionek",
block:"Format",
paragraph:"Akapit",
div:"Div",
address:"Adres",
pre:"Wstępnie sformatowany",
h1:"Nagłówek 1",
h2:"Nagłówek 2",
h3:"Nagłówek 3",
h4:"Nagłówek 4",
h5:"Nagłówek 5",
h6:"Nagłówek 6",
blockquote:"Blok cytatu",
code:"Kod",
samp:"Przykład",
dt:"Termin",
dd:"Definicja terminu",
bold_desc:"Pogrubienie (Ctrl+B)",
italic_desc:"Pochylenie (Ctrl+I)",
underline_desc:"Podkreślenie (Ctrl+U)",
striketrough_desc:"Przekreślenie",
justifyleft_desc:"Do lewej",
justifycenter_desc:"Wyśrodkuj",
justifyright_desc:"Do prawej",
justifyfull_desc:"Wyjustuj",
bullist_desc:"Wypunktowanie",
numlist_desc:"Numerowanie",
outdent_desc:"Zmniejsz wcięcie",
indent_desc:"Zwiększ wcięcie",
undo_desc:"Cofnij (Ctrl+Z)",
redo_desc:"Ponów (Ctrl+Y)",
link_desc:"Wstaw/Modyfikuj odnośnik",
unlink_desc:"Usuń odnośnik",
image_desc:"Wstaw/Modyfikuj obrazek",
cleanup_desc:"Wyczyść kod",
code_desc:"Edytuj kod źródłowy HTML",
sub_desc:"Indeks dolny",
sup_desc:"Indeks górny",
hr_desc:"Wstaw poziomą linię",
removeformat_desc:"Usuń formatowanie",
custom1_desc:"Twój opis",
forecolor_desc:"Wybierz kolor",
backcolor_desc:"Wybierz kolor tła",
charmap_desc:"Wstaw znak",
visualaid_desc:"Przełącznik prowadnic i elementów niewidocznych",
anchor_desc:"Wstaw/Modyfikuj zakładki",
cut_desc:"Wytnij",
copy_desc:"Kopiuj",
paste_desc:"Wklej",
image_props_desc:"Właściwości obrazka",
newdocument_desc:"Nowy dokument",
help_desc:"Pomoc",
blockquote_desc:"Blok cytatu",
clipboard_msg:"Opcje Kopiuj/Edytuj/Wklej nie są dostępne w przeglądarkach Mozilla i Firefox.\nPotrzebujesz wiecej informacji na ten temat?",
path:"Ścieżka",
newdocument:"Czy na pewno usunąć całą zawartość?",
toolbar_focus:"Idź do przycisków - Alt+Q, Idź do edytora - Alt-Z, Idź do ścieżki elementu - Alt-X",
more_colors:"Więcej kolorów"
});